"""Serving harness (generated by genproj).

Binds 0.0.0.0:3000, answers GET /healthz with 200 and a
JSON body ({"status": "ok"}), and serves the built frontend from
web/dist. This is the *harness* genproj guarantees: the
container comes up, serves the UI, and passes its own HEALTHCHECK. The wire
protocol and business endpoints are yours - replace this module with your
application.

Standard library only, so the generated project keeps zero runtime
dependencies.
"""

import os
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

DEFAULT_PORT = 3000
HEALTH_PATH = "/healthz"
# JSON, not a bare "ok": Homepage's `customapi` widget parses the health body
# as JSON, so a plain-text reply makes the dashboard tile error.
HEALTH_BODY = b'{"status": "ok"}'
STATIC_DIR = Path("web/dist")


class Handler(SimpleHTTPRequestHandler):
    """Serve STATIC_DIR, with the health path answered by hand."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(STATIC_DIR), **kwargs)

    def do_GET(self):
        if self.path.split("?", 1)[0] == HEALTH_PATH:
            body = HEALTH_BODY
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return
        super().do_GET()

    def log_message(self, fmt, *args):
        """Keep the default one-line-per-request stderr logging quiet."""


def main() -> int:
    port = int(os.environ.get("PORT", DEFAULT_PORT))
    server = ThreadingHTTPServer(("0.0.0.0", port), Handler)
    print(f"serving {STATIC_DIR} on http://0.0.0.0:{port}", flush=True)
    server.serve_forever()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
